# Generated by Django 5.2.7 on 2025-10-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_images/')),
                ('type_room', models.CharField(choices=[('standart', 'Standart'), ('lux', 'Lux'), ('suite', 'Suite')], default='standart', max_length=50)),
            ],
        ),
    ]
